dist: trusty
notifications:
  slack: ventureum-team:DSE8wxmLTenq0Yz17BrYBWg9
language: node_js
node_js:
  - 8
fail_fast: true
script:
- npm install eslint -g
- npm install babel-eslint -g
- npm install standard -g
- standard
- wget -P ./src/contracts/ https://s3.amazonaws.com/contracts.ventureum.io/prod/v2_proto/Milestone.json
- wget -P ./src/contracts/ https://s3.amazonaws.com/contracts.ventureum.io/prod/v2_proto/RepSys.json
- mv .env.prod .env
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJEWVYHFZZOVSRMOQ
  secret_access_key:
    secure: qcJuOg/gJvcvDmdOqK9tYaFyk+81Huo/MSFbyZ2DCJbLjvFwlIvN+TMlUIdpJePUHTiWsQe86uLrAo+EOoG8resfJ5RjIsxMj6IjZLXvpdOfnOdnRJmWcTDJQbUoUIZT5yo5Q3Wm7b6EexmXTENmxXmGhjijuf5qn4URpNwoesIvmdlPqsUNT2MSZjCuceiXp9D2HsT8knIHdatRxqtl6NSU45XK+b+tG1a40dtTUYA92dYJxSEUYB42iaeGC6oittY99PEod4N/rV1pZsJSow+8Pg5tCWSq3e+l1NWrEyqgMjqilhB0wS8bLXvN5S6PCw5xuHkBQI4b3K+AtgDh0BQ6u+rBgoB1eVdoA4DyPKSdoZkW2WibPrsaWhfOe7IX4dV4UCdEtlG6uEyZ12Vegy8Gqn4tVlc1VrUYYIIlaZfxWnSPV3QOYe8SjoY+Wk9TB++M8CmAyZu/XqruV3IrOb1S8H2L/Ml5hgM3Sc3iFwr6qYCouHCzXM8zm8ieQEyKGnZx2EkwOCylLrv6TCUq4e8UtEPm0iytXPB9O7uPleJnLQ2WQVpzDLUfBxOQG5QLBekB8kk8qLRAUXKWOV5qPRybQoUvC914rPAjhXlR9jsJhPfbmE/UkRS9Yn0+E8XhTmIySYSGq2v230osp3eVrSQ802m6K97Ro87MUbmfoDA= bucket: www.milest.one
  skip_cleanup: true
  local_dir: build
  region: ca-central-1
true:
  branch: master
