dist: trusty
notifications:
  slack: ventureum-team:DSE8wxmLTenq0Yz17BrYBWg9
language: node_js
node_js:
- 8
fail_fast: true
script:
- npm install eslint -g
- npm install babel-eslint -g
- npm install standard -g
- standard
- wget -P ./src/contracts/ https://s3.amazonaws.com/contracts.ventureum.io/prod/v2_proto/Milestone.json
- wget -P ./src/contracts/ https://s3.amazonaws.com/contracts.ventureum.io/prod/v2_proto/RepSys.json
- mv .env.prod .env
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJHR2FH2KJTDWH6YQ
  secret_access_key:
    secure: BrdpJCdhG1uXYmww7A5uXvprBG32Llepv0xVwyiK5Uhe5kFLPdFYiohokQ+UO5QA4Pr/rSRUYG4Dtj4tOLn2IyfJvQ/daY0uU1sfbLahqMmpzgoVR8lGkz1q76NgYjSJ1GSq7G66RuFsHZ2npFD0HA0wYpcPsy1iDFDkZW87vyNUOcAsuoXWY9g49kw/6b2QyXLyc+k1MZFpCzI4owiIdF2Aw8TCOe7UxL5FxYfmHUVUudY8JMf+V672/KlOeEgkIkWvFSdoQtowz/qmhxgiJAjJ6i4DY9A+aAlDgQD1piKlUoNJGFpwx0qqw52u7ZP4DQ+CkLZH4AVITQxVtguXTMzuOCnc4zyY8oIWEeVIg2pyxsBrx1wrO/xa9Mk1YiAYVxCvplcgNzpwZ5ZEtzn599Z+mlNv65u5zAwIDBbc92zllTcqVDiuvqK90Ootlti2TIBxYEZpFtH2ZI1gnEfOuqn88yv9g336L8qlp0iIs38ZFx4DzJaV5+/ZQKLfahEl3IQSTRMcWuYUWOh+sBeA/tQah2BGV8iAYJDTlPWrj4HmrWiXzqzc3fYAT1AjTiYQZ9//FBt8yPfU9sG07Mb6OoRnNck7Kpy3ubfWXb9sUv3tIImlhnZzWvFw0u+Dpv8i3eNKOOCMcnqqn7H1GDFiei+otvjSAOzMr+esckLdJBE=
  bucket: www.milest.one
  skip_cleanup: true
  local_dir: build
  region: ca-central-1
true:
  branch: master
